apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-angular
  namespace: prueba-angular
  labels:
    app: app-angular
spec:
  replicas: 2  # El número de réplicas que necesites
  selector:
    matchLabels:
      app: app-angular
  strategy:
    type: RollingUpdate  # Estrategia de actualización
    rollingUpdate:
      maxSurge: 1  # Máximo de pods adicionales durante la actualización
      maxUnavailable: 0  # Máximo de pods no disponibles durante la actualización
  template:
    metadata:
      labels:
        app: app-angular
    spec:
      containers:
      - name: mi-app-angular
        image: fcongedo/app-angular:2
        ports:
        - containerPort: 80